spring:
  application:
    name: notificaciones

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME:default_user}
    password: ${MAILTRAP_PASSWORD:default_password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  rabbitmq:
    exchange: compras.exchange
    queue: compras.notificaciones.queue
    routing-key: compras.realizadas.routing-key
